name: 'JWT Token Inspector'
description: 'Inspect a jwt token'
branding:
  icon: 'user-check'
  color: 'purple'
inputs:
    token:
        description: 'token to inspect'
        required: true
outputs:
    issuer:
        description: 'token issuer'
    subject:
        description: 'token subject'
    audience:
        description: 'token audience'
    claims-key:
        description: 'this is dynamic list of key-value, all keys are prefixed with "claims."'
runs:
    using: 'node20'
    main: 'dist/index.js'
