name: TokenTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  TokenTest:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Install Kubectl
      uses: azure/setup-kubectl@v4
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          let id_token = await core.getIDToken('test')
          core.setOutput('id_token', id_token)
          core.info(id_token.length)
    - name: Token Inspect
      id: tokenInspect
      uses: ./
      with:
        token: ${{ steps.idtoken.outputs.id_token }}
    - name: output consumers
      run: |
        echo "Issuer: ${{ steps.tokenInspect.outputs.issuer }}"
        echo "Subject: ${{ steps.tokenInspect.outputs.subject }}"
        echo "Audience: ${{ steps.tokenInspect.outputs.audience }}"
        echo "ref_type: ${{ steps.tokenInspect.outputs.claim_ref_type }}"
        echo "event_name: ${{ steps.tokenInspect.outputs.claim_event_name }}"
    - name: kubectlCommands
      run: |
        kubectl --token=${{ steps.idtoken.outputs.id_token }} --insecure-skip-tls-verify=true --server https://${{ secrets.KUBERNETES_SERVER }} get pods -A
